version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistem_gudang_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - sistem_gudang_network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_APP_KEY
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=sistemgudang
      - DB_USERNAME=root
      - DB_PASSWORD=
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=elian.hardiawan2001@gmail.com
      - MAIL_PASSWORD=qpvuzzwqxzcwejhr
      - MAIL_ENCRYPTION=tls
    ports:
      - "9000:9000"

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: sistem_gudang_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistem_gudang
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sistem_gudang_network

networks:
  sistem_gudang_network:
    driver: bridge

volumes:
  db_data:
    driver: local
